### PR TITLE
add ds4 config for x360

### PR DESCRIPTION
**Pull request by bb2020**

### CODE REVIEW

**Comment by bb2020** [comment]
Ping @matlo

**Comment by matlo** [comment]
Hi, I fixed the Dualshock4.xml config, it can be used with any target.

**Comment by matlo** [comment]
Thanks for reporting!

**Comment by bb2020** [comment]
Awesome. Is `shape="Circle"` deadzone setting needed for DS4? Other gamepad configs have that.

**Comment by matlo** [comment]
The shape is only used for mouse or key/button to axis mappings. At some point gimx-config was incorrectly allowing setting a shape value for joystick axis to axis mappings, which is why some configs may have it set.

**Comment by bb2020** [comment]
Oh, I see. Thanks for your reply and awesome Gimx project!

**Pull request closed without merging**
